apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: auto-report-rf0b
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: auto-report-rf0b
    app.kubernetes.io/part-of: auto-report
  name: auto-report-rf0b
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: auto-report-rf0b
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: auto-report-rf0b
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-migration-tenant/auto-report/auto-report-rf0b@sha256:5fb61228d304f6d93e2fc177ad018246488459820b63352868e32dc017cc9b52
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
