apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: auto-report-rf0b
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: auto-report-rf0b
    app.kubernetes.io/part-of: auto-report
  name: auto-report-rf0bcdf8
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: auto-report-rf0b
    weight: 100
status: {}
